import type { Node, NodeTypes } from "reactflow";
import { PositionLoggerNode } from "./PositionLoggerNode";

export const initialNodes = [
  { id: "a", type: "input", position: { x: 0, y: 0 }, data: { label: "wire" } },
  { id: "b", type: "position-logger", position: { x: -100, y: 100 }, data: { label: "drag me!" } },
  { id: "c", position: { x: 100, y: 100 }, data: { label: "your ideas" } },
  { id: "d", type: "output", position: { x: 0, y: 200 }, data: { label: "with React Flow" } },
  { id: "d", type: "output", position: { x: 0, y: 200 }, data: { label: "with React Flow" } },
  { id: "e", type: "input", position: { x: 150, y: 0 }, data: { label: "start" } },
  { id: "f", type: "output", position: { x: -150, y: 200 }, data: { label: "end" } },
  { id: "g", type: "default", position: { x: 50, y: 300 }, data: { label: "middle" } },
  { id: "h", type: "default", position: { x: 200, y: 400 }, data: { label: "step" } },
  { id: "i", type: "default", position: { x: -200, y: 400 }, data: { label: "step 2" } },
  { id: "j", type: "default", position: { x: 0, y: 500 }, data: { label: "finish" } },
  { id: "k", type: "input", position: { x: 250, y: 0 }, data: { label: "input 2" } },
  { id: "l", type: "output", position: { x: -250, y: 200 }, data: { label: "output 2" } },
  { id: "m", type: "default", position: { x: 100, y: 300 }, data: { label: "middle 2" } },
  { id: "n", type: "default", position: { x: 250, y: 400 }, data: { label: "step 3" } },
  { id: "o", type: "default", position: { x: -250, y: 400 }, data: { label: "step 4" } },
  { id: "p", type: "default", position: { x: 50, y: 600 }, data: { label: "complete" } },
  { id: "q", type: "input", position: { x: 350, y: 0 }, data: { label: "input 3" } },
  { id: "r", type: "output", position: { x: -350, y: 200 }, data: { label: "output 3" } },
  { id: "s", type: "default", position: { x: 150, y: 300 }, data: { label: "middle 3" } },
  { id: "t", type: "default", position: { x: 300, y: 400 }, data: { label: "step 5" } },
  { id: "u", type: "default", position: { x: -300, y: 400 }, data: { label: "step 6" } },
  { id: "v", type: "default", position: { x: 100, y: 700 }, data: { label: "done" } },
  { id: "w", type: "input", position: { x: 450, y: 0 }, data: { label: "input 4" } },
  { id: "x", type: "output", position: { x: -450, y: 200 }, data: { label: "output 4" } },
  { id: "y", type: "default", position: { x: 200, y: 300 }, data: { label: "middle 4" } },
  { id: "z", type: "default", position: { x: 350, y: 400 }, data: { label: "step 7" } },
  { id: "aa", type: "default", position: { x: -350, y: 400 }, data: { label: "step 8" } },
  { id: "ab", type: "default", position: { x: 150, y: 800 }, data: { label: "completed" } },
  { id: "ac", type: "input", position: { x: 550, y: 0 }, data: { label: "input 5" } },
  { id: "ad", type: "output", position: { x: -550, y: 200 }, data: { label: "output 5" } },
  { id: "ae", type: "default", position: { x: 250, y: 300 }, data: { label: "middle 5" } },
  { id: "af", type: "default", position: { x: 400, y: 400 }, data: { label: "step 9" } },
  { id: "ag", type: "default", position: { x: -400, y: 400 }, data: { label: "step 10" } },
  { id: "ah", type: "default", position: { x: 200, y: 900 }, data: { label: "conclusion" } },
  { id: "ai", type: "input", position: { x: 650, y: 0 }, data: { label: "input 6" } },
  { id: "aj", type: "output", position: { x: -650, y: 200 }, data: { label: "output 6" } },
  { id: "ak", type: "default", position: { x: 300, y: 300 }, data: { label: "middle 6" } },
  { id: "al", type: "default", position: { x: 450, y: 400 }, data: { label: "step 11" } },
  { id: "am", type: "default", position: { x: -450, y: 400 }, data: { label: "step 12" } },
  { id: "an", type: "default", position: { x: 250, y: 1000 }, data: { label: "final" } },
  { id: "ao", type: "input", position: { x: 750, y: 0 }, data: { label: "input 7" } },
  { id: "ap", type: "output", position: { x: -750, y: 200 }, data: { label: "output 7" } },
  { id: "aq", type: "default", position: { x: 350, y: 300 }, data: { label: "middle 7" } },
  { id: "ar", type: "default", position: { x: 500, y: 400 }, data: { label: "step 13" } },
  { id: "as", type: "default", position: { x: -500, y: 400 }, data: { label: "step 14" } },
  { id: "at", type: "default", position: { x: 300, y: 1100 }, data: { label: "wrap-up" } },
  { id: "au", type: "input", position: { x: 850, y: 0 }, data: { label: "input 8" } },
  { id: "av", type: "output", position: { x: -850, y: 200 }, data: { label: "output 8" } },
  { id: "aw", type: "default", position: { x: 400, y: 300 }, data: { label: "middle 8" } },
  { id: "ax", type: "default", position: { x: 550, y: 400 }, data: { label: "step 15" } },
  { id: "ay", type: "default", position: { x: -550, y: 400 }, data: { label: "step 16" } },
  { id: "az", type: "default", position: { x: 350, y: 1200 }, data: { label: "end" } },
] satisfies Node[];

export const nodeTypes = {

} satisfies NodeTypes;
